In [1]:
import pandas as pd

In [2]:
from sklearn.preprocessing import LabelEncoder,OrdinalEncoder

In [4]:
jailer=pd.read_csv("C:/Users/RANJITH BABU/Downloads/online_sales_dataset.csv")

In [5]:
jailer.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Discount,PaymentMethod,ShippingCost,Category,SalesChannel,ReturnStatus,ShipmentProvider,WarehouseLocation,OrderPriority
0,221958,SKU_1964,White Mug,38,2020-01-01 00:00,1.71,37039.0,Australia,0.470000,Bank Transfer,10.79,Apparel,In-store,Not Returned,UPS,London,Medium
1,771155,SKU_1241,White Mug,18,2020-01-01 01:00,41.25,19144.0,Spain,0.190000,paypall,9.51,Electronics,Online,Not Returned,UPS,Rome,Medium
2,231932,SKU_1501,Headphones,49,2020-01-01 02:00,29.11,50472.0,Germany,0.350000,Bank Transfer,23.03,Electronics,Online,Returned,UPS,Berlin,High
3,465838,SKU_1760,Desk Lamp,14,2020-01-01 03:00,76.68,96586.0,Netherlands,0.140000,paypall,11.08,Accessories,Online,Not Returned,Royal Mail,Rome,Low
4,359178,SKU_1386,USB Cable,-30,2020-01-01 04:00,-68.11,NaN,United Kingdom,1.501433,Bank Transfer,NaN,Electronics,In-store,Not Returned,FedEx,NaN,Medium

In [6]:
jailer.tail()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Discount,PaymentMethod,ShippingCost,Category,SalesChannel,ReturnStatus,ShipmentProvider,WarehouseLocation,OrderPriority
49777,354083,SKU_1562,Blue Pen,25,2025-09-05 01:00,70.92,51445.0,Spain,0.20,Credit Card,8.96,Electronics,Online,Returned,UPS,Berlin,Medium
49778,296698,SKU_1930,USB Cable,7,2025-09-05 02:00,51.74,28879.0,United States,0.23,Bank Transfer,23.55,Electronics,Online,Not Returned,FedEx,Amsterdam,Low
49779,177622,SKU_1766,Office Chair,43,2025-09-05 03:00,85.25,21825.0,Portugal,0.20,Bank Transfer,16.26,Furniture,In-store,Not Returned,FedEx,London,High
49780,701213,SKU_1602,Notebook,48,2025-09-05 04:00,39.64,43199.0,United Kingdom,0.31,paypall,28.56,Apparel,Online,Not Returned,Royal Mail,London,Medium
49781,772215,SKU_1832,White Mug,30,2025-09-05 05:00,38.27,53328.0,France,0.10,Credit Card,9.13,Stationery,Online,Not Returned,UPS,Rome,Low

In [7]:
jailer.shape

(49782, 17)

In [8]:
jailer.size

846294

In [10]:
jailer.columns

Index(['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'UnitPrice', 'CustomerID', 'Country', 'Discount', 'PaymentMethod',
       'ShippingCost', 'Category', 'SalesChannel', 'ReturnStatus',
       'ShipmentProvider', 'WarehouseLocation', 'OrderPriority'],
      dtype='str')

In [11]:
jailer.isnull()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Discount,PaymentMethod,ShippingCost,Category,SalesChannel,ReturnStatus,ShipmentProvider,WarehouseLocation,OrderPriority
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,True,False,False,False,True,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49777,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
49778,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
49779,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
49780,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
49781,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [12]:
jailer.isnull().sum()

InvoiceNo               0
StockCode               0
Description             0
Quantity                0
InvoiceDate             0
UnitPrice               0
CustomerID           4978
Country                 0
Discount                0
PaymentMethod           0
ShippingCost         2489
Category                0
SalesChannel            0
ReturnStatus            0
ShipmentProvider        0
WarehouseLocation    3485
OrderPriority           0
dtype: int64

In [14]:
jailer.duplicated().sum()

np.int64(0)

In [15]:
jailer.drop_duplicates()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Discount,PaymentMethod,ShippingCost,Category,SalesChannel,ReturnStatus,ShipmentProvider,WarehouseLocation,OrderPriority
0,221958,SKU_1964,White Mug,38,2020-01-01 00:00,1.71,37039.0,Australia,0.470000,Bank Transfer,10.79,Apparel,In-store,Not Returned,UPS,London,Medium
1,771155,SKU_1241,White Mug,18,2020-01-01 01:00,41.25,19144.0,Spain,0.190000,paypall,9.51,Electronics,Online,Not Returned,UPS,Rome,Medium
2,231932,SKU_1501,Headphones,49,2020-01-01 02:00,29.11,50472.0,Germany,0.350000,Bank Transfer,23.03,Electronics,Online,Returned,UPS,Berlin,High
3,465838,SKU_1760,Desk Lamp,14,2020-01-01 03:00,76.68,96586.0,Netherlands,0.140000,paypall,11.08,Accessories,Online,Not Returned,Royal Mail,Rome,Low
4,359178,SKU_1386,USB Cable,-30,2020-01-01 04:00,-68.11,NaN,United Kingdom,1.501433,Bank Transfer,NaN,Electronics,In-store,Not Returned,FedEx,NaN,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49777,354083,SKU_1562,Blue Pen,25,2025-09-05 01:00,70.92,51445.0,Spain,0.200000,Credit Card,8.96,Electronics,Online,Returned,UPS,Berlin,Medium
49778,296698,SKU_1930,USB Cable,7,2025-09-05 02:00,51.74,28879.0,United States,0.230000,Bank Transfer,23.55,Electronics,Online,Not Returned,FedEx,Amsterdam,Low
49779,177622,SKU_1766,Office Chair,43,2025-09-05 03:00,85.25,21825.0,Portugal,0.200000,Bank Transfer,16.26,Furniture,In-store,Not Returned,FedEx,London,High
49780,701213,SKU_1602,Notebook,48,2025-09-05 04:00,39.64,43199.0,United Kingdom,0.310000,paypall,28.56,Apparel,Online,Not Returned,Royal Mail,London,Medium
49781,772215,SKU_1832,White Mug,30,2025-09-05 05:00,38.27,53328.0,France,0.100000,Credit Card,9.13,Stationery,Online,Not Returned,UPS,Rome,Low

In [16]:
jailer.drop_duplicates(inplace=True)

In [18]:
pd.to_datetime(jailer["InvoiceDate"])

0       2020-01-01 00:00:00
1       2020-01-01 01:00:00
2       2020-01-01 02:00:00
3       2020-01-01 03:00:00
4       2020-01-01 04:00:00
                ...
49777   2025-09-05 01:00:00
49778   2025-09-05 02:00:00
49779   2025-09-05 03:00:00
49780   2025-09-05 04:00:00
49781   2025-09-05 05:00:00
Name: InvoiceDate, Length: 49782, dtype: datetime64[us]

In [19]:
jailer.loc[0:7,["InvoiceDate","Description"]]

        InvoiceDate   Description
0  2020-01-01 00:00     White Mug
1  2020-01-01 01:00     White Mug
2  2020-01-01 02:00    Headphones
3  2020-01-01 03:00     Desk Lamp
4  2020-01-01 04:00     USB Cable
5  2020-01-01 05:00  Office Chair
6  2020-01-01 06:00     USB Cable
7  2020-01-01 07:00      Notebook

In [20]:
jailer.iloc[0:5,0:4]

   InvoiceNo StockCode Description  Quantity
0     221958  SKU_1964   White Mug        38
1     771155  SKU_1241   White Mug        18
2     231932  SKU_1501  Headphones        49
3     465838  SKU_1760   Desk Lamp        14
4     359178  SKU_1386   USB Cable       -30

In [21]:
jailer[jailer["Quantity"]>20]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Discount,PaymentMethod,ShippingCost,Category,SalesChannel,ReturnStatus,ShipmentProvider,WarehouseLocation,OrderPriority
0,221958,SKU_1964,White Mug,38,2020-01-01 00:00,1.71,37039.0,Australia,0.47,Bank Transfer,10.79,Apparel,In-store,Not Returned,UPS,London,Medium
2,231932,SKU_1501,Headphones,49,2020-01-01 02:00,29.11,50472.0,Germany,0.35,Bank Transfer,23.03,Electronics,Online,Returned,UPS,Berlin,High
5,744167,SKU_1006,Office Chair,47,2020-01-01 05:00,70.16,53887.0,Sweden,0.48,Credit Card,13.98,Electronics,Online,Not Returned,DHL,London,Medium
6,210268,SKU_1087,USB Cable,25,2020-01-01 06:00,85.74,46567.0,Belgium,0.15,Bank Transfer,12.92,Stationery,Online,Not Returned,FedEx,Amsterdam,High
9,237337,SKU_1866,Headphones,40,2020-01-01 09:00,98.17,39718.0,Italy,0.16,Bank Transfer,7.71,Apparel,Online,Not Returned,Royal Mail,London,Low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49776,524453,SKU_1316,Office Chair,43,2025-09-05 00:00,84.19,84399.0,United Kingdom,0.25,Credit Card,21.38,Electronics,Online,Not Returned,DHL,Amsterdam,Low
49777,354083,SKU_1562,Blue Pen,25,2025-09-05 01:00,70.92,51445.0,Spain,0.20,Credit Card,8.96,Electronics,Online,Returned,UPS,Berlin,Medium
49779,177622,SKU_1766,Office Chair,43,2025-09-05 03:00,85.25,21825.0,Portugal,0.20,Bank Transfer,16.26,Furniture,In-store,Not Returned,FedEx,London,High
49780,701213,SKU_1602,Notebook,48,2025-09-05 04:00,39.64,43199.0,United Kingdom,0.31,paypall,28.56,Apparel,Online,Not Returned,Royal Mail,London,Medium
49781,772215,SKU_1832,White Mug,30,2025-09-05 05:00,38.27,53328.0,France,0.10,Credit Card,9.13,Stationery,Online,Not Returned,UPS,Rome,Low

In [22]:
jailer[jailer["Quantity"]<20]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Discount,PaymentMethod,ShippingCost,Category,SalesChannel,ReturnStatus,ShipmentProvider,WarehouseLocation,OrderPriority
1,771155,SKU_1241,White Mug,18,2020-01-01 01:00,41.25,19144.0,Spain,0.190000,paypall,9.51,Electronics,Online,Not Returned,UPS,Rome,Medium
3,465838,SKU_1760,Desk Lamp,14,2020-01-01 03:00,76.68,96586.0,Netherlands,0.140000,paypall,11.08,Accessories,Online,Not Returned,Royal Mail,Rome,Low
4,359178,SKU_1386,USB Cable,-30,2020-01-01 04:00,-68.11,NaN,United Kingdom,1.501433,Bank Transfer,NaN,Electronics,In-store,Not Returned,FedEx,NaN,Medium
7,832180,SKU_1597,Notebook,8,2020-01-01 07:00,95.65,75098.0,Norway,0.040000,Bank Transfer,6.48,Electronics,In-store,Not Returned,Royal Mail,Amsterdam,Low
8,154886,SKU_1907,Wireless Mouse,19,2020-01-01 08:00,98.19,87950.0,Belgium,0.050000,paypall,12.56,Apparel,Online,Not Returned,UPS,Berlin,High
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49769,701257,SKU_1092,Office Chair,19,2025-09-04 17:00,81.91,64156.0,Belgium,0.480000,Bank Transfer,13.45,Stationery,In-store,Returned,DHL,Paris,Medium
49770,625657,SKU_1628,Office Chair,-30,2025-09-04 18:00,16.82,NaN,France,0.340000,Credit Card,NaN,Electronics,Online,Not Returned,DHL,NaN,Low
49771,376212,SKU_1936,Notebook,1,2025-09-04 19:00,16.51,36515.0,Norway,0.010000,paypall,26.65,Electronics,In-store,Not Returned,FedEx,Berlin,Low
49773,370260,SKU_1570,Blue Pen,12,2025-09-04 21:00,51.83,85250.0,Italy,0.320000,Credit Card,22.44,Accessories,In-store,Not Returned,Royal Mail,Rome,Medium
49778,296698,SKU_1930,USB Cable,7,2025-09-05 02:00,51.74,28879.0,United States,0.230000,Bank Transfer,23.55,Electronics,Online,Not Returned,FedEx,Amsterdam,Low

In [23]:
jailer[jailer["Quantity"]==20]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Discount,PaymentMethod,ShippingCost,Category,SalesChannel,ReturnStatus,ShipmentProvider,WarehouseLocation,OrderPriority
45,184654,SKU_1259,Wall Clock,20,2020-01-02 21:00,24.36,73680.0,Norway,0.07,Bank Transfer,18.99,Apparel,In-store,Not Returned,FedEx,London,High
65,517113,SKU_1946,Notebook,20,2020-01-03 17:00,39.00,43390.0,Italy,0.09,paypall,21.67,Electronics,Online,Not Returned,Royal Mail,Berlin,Medium
85,415139,SKU_1589,USB Cable,20,2020-01-04 13:00,49.92,62514.0,Germany,0.40,Bank Transfer,8.34,Electronics,Online,Not Returned,Royal Mail,Rome,Low
112,616588,SKU_1813,USB Cable,20,2020-01-05 16:00,84.61,19020.0,Norway,0.26,Bank Transfer,11.70,Stationery,In-store,Not Returned,FedEx,Paris,High
150,373109,SKU_1671,White Mug,20,2020-01-07 06:00,28.40,44898.0,Netherlands,0.49,Credit Card,28.77,Electronics,Online,Not Returned,UPS,Amsterdam,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49305,889842,SKU_1265,Blue Pen,20,2025-08-16 09:00,57.11,94185.0,United Kingdom,0.04,paypall,10.26,Furniture,Online,Not Returned,Royal Mail,Berlin,High
49361,717662,SKU_1982,T-shirt,20,2025-08-18 17:00,36.10,93264.0,Norway,0.10,Credit Card,5.17,Furniture,In-store,Not Returned,FedEx,Berlin,Low
49624,269008,SKU_1548,USB Cable,20,2025-08-29 16:00,12.35,90208.0,United Kingdom,0.48,Credit Card,12.13,Stationery,In-store,Not Returned,UPS,Berlin,Low
49685,516911,SKU_1742,Wireless Mouse,20,2025-09-01 05:00,48.76,NaN,Germany,0.50,Bank Transfer,27.65,Accessories,Online,Not Returned,Royal Mail,London,High
49716,706303,SKU_1830,Notebook,20,2025-09-02 12:00,8.03,18560.0,Portugal,0.03,paypall,13.38,Accessories,Online,Returned,UPS,Rome,Medium

In [24]:
jailer[~(jailer["Quantity"]>20)]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Discount,PaymentMethod,ShippingCost,Category,SalesChannel,ReturnStatus,ShipmentProvider,WarehouseLocation,OrderPriority
1,771155,SKU_1241,White Mug,18,2020-01-01 01:00,41.25,19144.0,Spain,0.190000,paypall,9.51,Electronics,Online,Not Returned,UPS,Rome,Medium
3,465838,SKU_1760,Desk Lamp,14,2020-01-01 03:00,76.68,96586.0,Netherlands,0.140000,paypall,11.08,Accessories,Online,Not Returned,Royal Mail,Rome,Low
4,359178,SKU_1386,USB Cable,-30,2020-01-01 04:00,-68.11,NaN,United Kingdom,1.501433,Bank Transfer,NaN,Electronics,In-store,Not Returned,FedEx,NaN,Medium
7,832180,SKU_1597,Notebook,8,2020-01-01 07:00,95.65,75098.0,Norway,0.040000,Bank Transfer,6.48,Electronics,In-store,Not Returned,Royal Mail,Amsterdam,Low
8,154886,SKU_1907,Wireless Mouse,19,2020-01-01 08:00,98.19,87950.0,Belgium,0.050000,paypall,12.56,Apparel,Online,Not Returned,UPS,Berlin,High
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49769,701257,SKU_1092,Office Chair,19,2025-09-04 17:00,81.91,64156.0,Belgium,0.480000,Bank Transfer,13.45,Stationery,In-store,Returned,DHL,Paris,Medium
49770,625657,SKU_1628,Office Chair,-30,2025-09-04 18:00,16.82,NaN,France,0.340000,Credit Card,NaN,Electronics,Online,Not Returned,DHL,NaN,Low
49771,376212,SKU_1936,Notebook,1,2025-09-04 19:00,16.51,36515.0,Norway,0.010000,paypall,26.65,Electronics,In-store,Not Returned,FedEx,Berlin,Low
49773,370260,SKU_1570,Blue Pen,12,2025-09-04 21:00,51.83,85250.0,Italy,0.320000,Credit Card,22.44,Accessories,In-store,Not Returned,Royal Mail,Rome,Medium
49778,296698,SKU_1930,USB Cable,7,2025-09-05 02:00,51.74,28879.0,United States,0.230000,Bank Transfer,23.55,Electronics,Online,Not Returned,FedEx,Amsterdam,Low

In [25]:
jailer["Data"]=jailer["ShippingCost"]*jailer["CustomerID"]
print(jailer)

       InvoiceNo StockCode   Description  Quantity       InvoiceDate  \
0         221958  SKU_1964     White Mug        38  2020-01-01 00:00
1         771155  SKU_1241     White Mug        18  2020-01-01 01:00
2         231932  SKU_1501    Headphones        49  2020-01-01 02:00
3         465838  SKU_1760     Desk Lamp        14  2020-01-01 03:00
4         359178  SKU_1386     USB Cable       -30  2020-01-01 04:00
...          ...       ...           ...       ...               ...
49777     354083  SKU_1562      Blue Pen        25  2025-09-05 01:00
49778     296698  SKU_1930     USB Cable         7  2025-09-05 02:00
49779     177622  SKU_1766  Office Chair        43  2025-09-05 03:00
49780     701213  SKU_1602      Notebook        48  2025-09-05 04:00
49781     772215  SKU_1832     White Mug        30  2025-09-05 05:00

       UnitPrice  CustomerID         Country  Discount  PaymentMethod  \
0           1.71     37039.0       Australia  0.470000  Bank Transfer
1          41.25     19144.0           Spain  0.190000        paypall
2          29.11     50472.0         Germany  0.350000  Bank Transfer
3          76.68     96586.0     Netherlands  0.140000        paypall
4         -68.11         NaN  United Kingdom  1.501433  Bank Transfer
...          ...         ...             ...       ...            ...
49777      70.92     51445.0           Spain  0.200000    Credit Card
49778      51.74     28879.0   United States  0.230000  Bank Transfer
49779      85.25     21825.0        Portugal  0.200000  Bank Transfer
49780      39.64     43199.0  United Kingdom  0.310000        paypall
49781      38.27     53328.0          France  0.100000    Credit Card

       ShippingCost     Category SalesChannel  ReturnStatus ShipmentProvider  \
0             10.79      Apparel     In-store  Not Returned              UPS
1              9.51  Electronics       Online  Not Returned              UPS
2             23.03  Electronics       Online      Returned              UPS
3             11.08  Accessories       Online  Not Returned       Royal Mail
4               NaN  Electronics     In-store  Not Returned            FedEx
...             ...          ...          ...           ...              ...
49777          8.96  Electronics       Online      Returned              UPS
49778         23.55  Electronics       Online  Not Returned            FedEx
49779         16.26    Furniture     In-store  Not Returned            FedEx
49780         28.56      Apparel       Online  Not Returned       Royal Mail
49781          9.13   Stationery       Online  Not Returned              UPS

      WarehouseLocation OrderPriority        Data
0                London        Medium   399650.81
1                  Rome        Medium   182059.44
2                Berlin          High  1162370.16
3                  Rome           Low  1070172.88
4                   NaN        Medium         NaN
...                 ...           ...         ...
49777            Berlin        Medium   460947.20
49778         Amsterdam           Low   680100.45
49779            London          High   354874.50
49780            London        Medium  1233763.44
49781              Rome           Low   486884.64

[49782 rows x 18 columns]

In [26]:
jailer["Data"]=jailer["ShippingCost"]+jailer["CustomerID"]
print(jailer)

       InvoiceNo StockCode   Description  Quantity       InvoiceDate  \
0         221958  SKU_1964     White Mug        38  2020-01-01 00:00
1         771155  SKU_1241     White Mug        18  2020-01-01 01:00
2         231932  SKU_1501    Headphones        49  2020-01-01 02:00
3         465838  SKU_1760     Desk Lamp        14  2020-01-01 03:00
4         359178  SKU_1386     USB Cable       -30  2020-01-01 04:00
...          ...       ...           ...       ...               ...
49777     354083  SKU_1562      Blue Pen        25  2025-09-05 01:00
49778     296698  SKU_1930     USB Cable         7  2025-09-05 02:00
49779     177622  SKU_1766  Office Chair        43  2025-09-05 03:00
49780     701213  SKU_1602      Notebook        48  2025-09-05 04:00
49781     772215  SKU_1832     White Mug        30  2025-09-05 05:00

       UnitPrice  CustomerID         Country  Discount  PaymentMethod  \
0           1.71     37039.0       Australia  0.470000  Bank Transfer
1          41.25     19144.0           Spain  0.190000        paypall
2          29.11     50472.0         Germany  0.350000  Bank Transfer
3          76.68     96586.0     Netherlands  0.140000        paypall
4         -68.11         NaN  United Kingdom  1.501433  Bank Transfer
...          ...         ...             ...       ...            ...
49777      70.92     51445.0           Spain  0.200000    Credit Card
49778      51.74     28879.0   United States  0.230000  Bank Transfer
49779      85.25     21825.0        Portugal  0.200000  Bank Transfer
49780      39.64     43199.0  United Kingdom  0.310000        paypall
49781      38.27     53328.0          France  0.100000    Credit Card

       ShippingCost     Category SalesChannel  ReturnStatus ShipmentProvider  \
0             10.79      Apparel     In-store  Not Returned              UPS
1              9.51  Electronics       Online  Not Returned              UPS
2             23.03  Electronics       Online      Returned              UPS
3             11.08  Accessories       Online  Not Returned       Royal Mail
4               NaN  Electronics     In-store  Not Returned            FedEx
...             ...          ...          ...           ...              ...
49777          8.96  Electronics       Online      Returned              UPS
49778         23.55  Electronics       Online  Not Returned            FedEx
49779         16.26    Furniture     In-store  Not Returned            FedEx
49780         28.56      Apparel       Online  Not Returned       Royal Mail
49781          9.13   Stationery       Online  Not Returned              UPS

      WarehouseLocation OrderPriority      Data
0                London        Medium  37049.79
1                  Rome        Medium  19153.51
2                Berlin          High  50495.03
3                  Rome           Low  96597.08
4                   NaN        Medium       NaN
...                 ...           ...       ...
49777            Berlin        Medium  51453.96
49778         Amsterdam           Low  28902.55
49779            London          High  21841.26
49780            London        Medium  43227.56
49781              Rome           Low  53337.13

[49782 rows x 18 columns]

In [27]:
jailer["Data"]=jailer["ShippingCost"]%jailer["CustomerID"]
print(jailer)

       InvoiceNo StockCode   Description  Quantity       InvoiceDate  \
0         221958  SKU_1964     White Mug        38  2020-01-01 00:00
1         771155  SKU_1241     White Mug        18  2020-01-01 01:00
2         231932  SKU_1501    Headphones        49  2020-01-01 02:00
3         465838  SKU_1760     Desk Lamp        14  2020-01-01 03:00
4         359178  SKU_1386     USB Cable       -30  2020-01-01 04:00
...          ...       ...           ...       ...               ...
49777     354083  SKU_1562      Blue Pen        25  2025-09-05 01:00
49778     296698  SKU_1930     USB Cable         7  2025-09-05 02:00
49779     177622  SKU_1766  Office Chair        43  2025-09-05 03:00
49780     701213  SKU_1602      Notebook        48  2025-09-05 04:00
49781     772215  SKU_1832     White Mug        30  2025-09-05 05:00

       UnitPrice  CustomerID         Country  Discount  PaymentMethod  \
0           1.71     37039.0       Australia  0.470000  Bank Transfer
1          41.25     19144.0           Spain  0.190000        paypall
2          29.11     50472.0         Germany  0.350000  Bank Transfer
3          76.68     96586.0     Netherlands  0.140000        paypall
4         -68.11         NaN  United Kingdom  1.501433  Bank Transfer
...          ...         ...             ...       ...            ...
49777      70.92     51445.0           Spain  0.200000    Credit Card
49778      51.74     28879.0   United States  0.230000  Bank Transfer
49779      85.25     21825.0        Portugal  0.200000  Bank Transfer
49780      39.64     43199.0  United Kingdom  0.310000        paypall
49781      38.27     53328.0          France  0.100000    Credit Card

       ShippingCost     Category SalesChannel  ReturnStatus ShipmentProvider  \
0             10.79      Apparel     In-store  Not Returned              UPS
1              9.51  Electronics       Online  Not Returned              UPS
2             23.03  Electronics       Online      Returned              UPS
3             11.08  Accessories       Online  Not Returned       Royal Mail
4               NaN  Electronics     In-store  Not Returned            FedEx
...             ...          ...          ...           ...              ...
49777          8.96  Electronics       Online      Returned              UPS
49778         23.55  Electronics       Online  Not Returned            FedEx
49779         16.26    Furniture     In-store  Not Returned            FedEx
49780         28.56      Apparel       Online  Not Returned       Royal Mail
49781          9.13   Stationery       Online  Not Returned              UPS

      WarehouseLocation OrderPriority   Data
0                London        Medium  10.79
1                  Rome        Medium   9.51
2                Berlin          High  23.03
3                  Rome           Low  11.08
4                   NaN        Medium    NaN
...                 ...           ...    ...
49777            Berlin        Medium   8.96
49778         Amsterdam           Low  23.55
49779            London          High  16.26
49780            London        Medium  28.56
49781              Rome           Low   9.13

[49782 rows x 18 columns]

In [28]:
jailer["Data"]=jailer["ShippingCost"]-jailer["CustomerID"]
print(jailer)

       InvoiceNo StockCode   Description  Quantity       InvoiceDate  \
0         221958  SKU_1964     White Mug        38  2020-01-01 00:00
1         771155  SKU_1241     White Mug        18  2020-01-01 01:00
2         231932  SKU_1501    Headphones        49  2020-01-01 02:00
3         465838  SKU_1760     Desk Lamp        14  2020-01-01 03:00
4         359178  SKU_1386     USB Cable       -30  2020-01-01 04:00
...          ...       ...           ...       ...               ...
49777     354083  SKU_1562      Blue Pen        25  2025-09-05 01:00
49778     296698  SKU_1930     USB Cable         7  2025-09-05 02:00
49779     177622  SKU_1766  Office Chair        43  2025-09-05 03:00
49780     701213  SKU_1602      Notebook        48  2025-09-05 04:00
49781     772215  SKU_1832     White Mug        30  2025-09-05 05:00

       UnitPrice  CustomerID         Country  Discount  PaymentMethod  \
0           1.71     37039.0       Australia  0.470000  Bank Transfer
1          41.25     19144.0           Spain  0.190000        paypall
2          29.11     50472.0         Germany  0.350000  Bank Transfer
3          76.68     96586.0     Netherlands  0.140000        paypall
4         -68.11         NaN  United Kingdom  1.501433  Bank Transfer
...          ...         ...             ...       ...            ...
49777      70.92     51445.0           Spain  0.200000    Credit Card
49778      51.74     28879.0   United States  0.230000  Bank Transfer
49779      85.25     21825.0        Portugal  0.200000  Bank Transfer
49780      39.64     43199.0  United Kingdom  0.310000        paypall
49781      38.27     53328.0          France  0.100000    Credit Card

       ShippingCost     Category SalesChannel  ReturnStatus ShipmentProvider  \
0             10.79      Apparel     In-store  Not Returned              UPS
1              9.51  Electronics       Online  Not Returned              UPS
2             23.03  Electronics       Online      Returned              UPS
3             11.08  Accessories       Online  Not Returned       Royal Mail
4               NaN  Electronics     In-store  Not Returned            FedEx
...             ...          ...          ...           ...              ...
49777          8.96  Electronics       Online      Returned              UPS
49778         23.55  Electronics       Online  Not Returned            FedEx
49779         16.26    Furniture     In-store  Not Returned            FedEx
49780         28.56      Apparel       Online  Not Returned       Royal Mail
49781          9.13   Stationery       Online  Not Returned              UPS

      WarehouseLocation OrderPriority      Data
0                London        Medium -37028.21
1                  Rome        Medium -19134.49
2                Berlin          High -50448.97
3                  Rome           Low -96574.92
4                   NaN        Medium       NaN
...                 ...           ...       ...
49777            Berlin        Medium -51436.04
49778         Amsterdam           Low -28855.45
49779            London          High -21808.74
49780            London        Medium -43170.44
49781              Rome           Low -53318.87

[49782 rows x 18 columns]

In [29]:
jailer.groupby("CustomerID")["Data"].min()

CustomerID
10001.0    -9977.82
10003.0    -9991.91
10005.0    -9979.39
10008.0    -9985.20
10009.0    -9985.36
             ...
99986.0   -99974.47
99989.0   -99965.55
99993.0   -99973.69
99997.0   -99982.08
99998.0   -99989.73
Name: Data, Length: 35389, dtype: float64

In [30]:
jailer.groupby("CustomerID")["Data"].max()

CustomerID
10001.0    -9977.82
10003.0    -9991.91
10005.0    -9977.49
10008.0    -9985.20
10009.0    -9985.36
             ...
99986.0   -99962.38
99989.0   -99965.55
99993.0   -99973.69
99997.0   -99982.08
99998.0   -99977.69
Name: Data, Length: 35389, dtype: float64

In [31]:
jailer.groupby("CustomerID")["Data"].sum()

CustomerID
10001.0     -9977.82
10003.0     -9991.91
10005.0    -19956.88
10008.0     -9985.20
10009.0     -9985.36
             ...
99986.0   -199936.85
99989.0    -99965.55
99993.0    -99973.69
99997.0    -99982.08
99998.0   -199967.42
Name: Data, Length: 35389, dtype: float64

In [32]:
jailer.groupby("CustomerID")["Data"].std()

CustomerID
10001.0         NaN
10003.0         NaN
10005.0    1.343503
10008.0         NaN
10009.0         NaN
             ...
99986.0    8.548921
99989.0         NaN
99993.0         NaN
99997.0         NaN
99998.0    8.513566
Name: Data, Length: 35389, dtype: float64

In [33]:
cd=LabelEncoder()
jailer["Order"]=cd.fit_transform(jailer["OrderPriority"])
jailer.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Discount,PaymentMethod,ShippingCost,Category,SalesChannel,ReturnStatus,ShipmentProvider,WarehouseLocation,OrderPriority,Data,Order
0,221958,SKU_1964,White Mug,38,2020-01-01 00:00,1.71,37039.0,Australia,0.470000,Bank Transfer,10.79,Apparel,In-store,Not Returned,UPS,London,Medium,-37028.21,2
1,771155,SKU_1241,White Mug,18,2020-01-01 01:00,41.25,19144.0,Spain,0.190000,paypall,9.51,Electronics,Online,Not Returned,UPS,Rome,Medium,-19134.49,2
2,231932,SKU_1501,Headphones,49,2020-01-01 02:00,29.11,50472.0,Germany,0.350000,Bank Transfer,23.03,Electronics,Online,Returned,UPS,Berlin,High,-50448.97,0
3,465838,SKU_1760,Desk Lamp,14,2020-01-01 03:00,76.68,96586.0,Netherlands,0.140000,paypall,11.08,Accessories,Online,Not Returned,Royal Mail,Rome,Low,-96574.92,1
4,359178,SKU_1386,USB Cable,-30,2020-01-01 04:00,-68.11,NaN,United Kingdom,1.501433,Bank Transfer,NaN,Electronics,In-store,Not Returned,FedEx,NaN,Medium,NaN,2

In [34]:
oe=OrdinalEncoder(categories=[["In-store", "Online",]])
jailer["Channel"]=oe.fit_transform(jailer[["SalesChannel"]])
jailer.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Discount,PaymentMethod,ShippingCost,Category,SalesChannel,ReturnStatus,ShipmentProvider,WarehouseLocation,OrderPriority,Data,Order,Channel
0,221958,SKU_1964,White Mug,38,2020-01-01 00:00,1.71,37039.0,Australia,0.470000,Bank Transfer,10.79,Apparel,In-store,Not Returned,UPS,London,Medium,-37028.21,2,0.0
1,771155,SKU_1241,White Mug,18,2020-01-01 01:00,41.25,19144.0,Spain,0.190000,paypall,9.51,Electronics,Online,Not Returned,UPS,Rome,Medium,-19134.49,2,1.0
2,231932,SKU_1501,Headphones,49,2020-01-01 02:00,29.11,50472.0,Germany,0.350000,Bank Transfer,23.03,Electronics,Online,Returned,UPS,Berlin,High,-50448.97,0,1.0
3,465838,SKU_1760,Desk Lamp,14,2020-01-01 03:00,76.68,96586.0,Netherlands,0.140000,paypall,11.08,Accessories,Online,Not Returned,Royal Mail,Rome,Low,-96574.92,1,1.0
4,359178,SKU_1386,USB Cable,-30,2020-01-01 04:00,-68.11,NaN,United Kingdom,1.501433,Bank Transfer,NaN,Electronics,In-store,Not Returned,FedEx,NaN,Medium,NaN,2,0.0

In [ ]:
df=pd.get_dummies(df,columns=["Country"],dtype=int)
df.head()